name = "lpc55xpresso"
target = "thumbv8m.main-none-eabihf"
board = "lpcxpresso55s69"
chip = "../../chips/lpc55"
secure-separation = true
image-names = ["stage0"]
external-images = ["a", "b"]

[kernel]
name = "stage0"
requires = {flash = 0x9000, ram = 16000}
features = ["tz_support", "dice-self"]
stacksize = 13000

[tasks.idle]
name = "task-idle"
priority = 0
max-sizes = {flash = 256, ram = 256}
stacksize = 256
start = true

[signing]
enable-secure-boot = true
enable-dice = true
dice-inc-nxp-cfg = false
dice-cust-cfg = false
dice-inc-sec-epoch = false

[[signing.certs]]
cert-paths = ["../../support/fake_certs/pki_playground/TEST USE ONLY - Gimlet RoT Stage0 Code Signing Engineering Offline CA A Trust Anchor.cert.der", 
  "../../support/fake_certs/pki_playground/TEST USE ONLY - Gimlet RoT Stage0 Code Signing Engineering Online Signer A1.cert.der" ]
priv-key = "../../support/fake_certs/pki_playground/TEST USE ONLY - Gimlet RoT Stage0 Code Signing Engineering Online Signer A1.key.pem"

[[signing.certs]]
cert-paths = ["../../support/fake_certs/pki_playground/TEST USE ONLY - Gimlet RoT Stage0 Code Signing Engineering Offline CA B Trust Anchor.cert.der"]

[[signing.certs]]
cert-paths = ["../../support/fake_certs/pki_playground/TEST USE ONLY - Gimlet RoT Stage0 Code Signing Production Offline CA A Trust Anchor.cert.der"]

[[signing.certs]]
cert-paths = ["../../support/fake_certs/pki_playground/TEST USE ONLY - Gimlet RoT Stage0 Code Signing Production Offline CA B Trust Anchor.cert.der"]
